### ISSUE TITLE
BANNING A SPAMMING ACCOUND BRO THIS IS A FAKE ACCOUND WHICH SPAMS PEOPLE CAN YOU PLEASE BAN THIS ACCOUND https://instagram.com/bavanthi_varsitha?igshid=YmMyMTA2M2Y= I DONT KNOW HOW TO USE THIS TOOL BUT HOPE YOU WILL HELP ME

### ISSUE THREAD

**Issue by JAGHDHEEP** [TroyD1/Instagram-Auto-Report-2023#1]
BRO THIS IS A FAKE ACCOUND WHICH SPAMS PEOPLE CAN YOU PLEASE BAN THIS ACCOUND 
https://instagram.com/bavanthi_varsitha?igshid=YmMyMTA2M2Y=
 I DONT KNOW HOW TO USE THIS TOOL BUT HOPE YOU WILL HELP ME

**Comment by TroyD1** [comment]
pm me on telegram https://t.me/sniper_spy
